package co.com.sura.distribucion.asignacion.node.commons.constants

/**
 * Define constantes referentes al cluster.
 */
object LogConstants {

  private val CONSTANT_PREFIX = "log."

  lazy val SEED_STARTED: String = Constants.getString("SEED_STARTED", CONSTANT_PREFIX)
  lazy val CLIENT_STARTED: String = Constants.getString("CLIENT_STARTED", CONSTANT_PREFIX)
  lazy val NODE_STARTED: String = Constants.getString("NODE_STARTED", CONSTANT_PREFIX)
  lazy val ACTOR_UNKNOWN_MSG: String = Constants.getString("ACTOR_UNKNOWN_MSG", CONSTANT_PREFIX)
  lazy val NEW_NODE_LEADER: String = Constants.getString("NEW_NODE_LEADER", CONSTANT_PREFIX)
  lazy val ACTOR_STATE: String = Constants.getString("ACTOR_STATE", CONSTANT_PREFIX)
  lazy val SYSTEM_NOT_RECOVERED: String = Constants.getString("SYSTEM_NOT_RECOVERED", CONSTANT_PREFIX)
  lazy val PERSISTENT_ACTOR_STASH_FULL: String = Constants.getString("PERSISTENT_ACTOR_STASH_FULL", CONSTANT_PREFIX)
  lazy val PERSISTENT_ACTOR_ERROR: String = Constants.getString("PERSISTENT_ACTOR_ERROR", CONSTANT_PREFIX)
  lazy val PERSISTENT_ACTOR_RECOVERY_UNKNOWN: String = Constants.getString("PERSISTENT_ACTOR_RECOVERY_UNKNOWN", CONSTANT_PREFIX)
  lazy val PERSISTENT_ACTOR_PERSIST_UNKNOWN: String = Constants.getString("PERSISTENT_ACTOR_PERSIST_UNKNOWN", CONSTANT_PREFIX)
  lazy val PERSISTENT_ACTOR_RECOVERY_RETRY: String = Constants.getString("PERSISTENT_ACTOR_RECOVERY_RETRY", CONSTANT_PREFIX)
  lazy val PERSISTENT_ACTOR_NOT_PERSISTENCE_LAYER: String = Constants.getString("PERSISTENT_ACTOR_NOT_PERSISTENCE_LAYER", CONSTANT_PREFIX)
  lazy val PERSISTENT_ACTOR_NOT_PERSISTENCE_TOKEN: String = Constants.getString("PERSISTENT_ACTOR_NOT_PERSISTENCE_TOKEN", CONSTANT_PREFIX)
  lazy val PERSISTENCE_LAYER_RECOVERY_ERROR: String = Constants.getString("PERSISTENCE_LAYER_RECOVERY_ERROR", CONSTANT_PREFIX)
  lazy val PERSISTENCE_LAYER_RECOVERY_SUCCESS: String = Constants.getString("PERSISTENCE_LAYER_RECOVERY_SUCCESS", CONSTANT_PREFIX)
  lazy val PERSISTENCE_LAYER_RECOVERY_UNKNOWN: String = Constants.getString("PERSISTENCE_LAYER_RECOVERY_UNKNOWN", CONSTANT_PREFIX)
  lazy val PERSISTENCE_LAYER_PERSIST_ERROR: String = Constants.getString("PERSISTENCE_LAYER_PERSIST_ERROR", CONSTANT_PREFIX)
  lazy val PERSISTENCE_LAYER_PERSIST_STATE_ERROR: String = Constants.getString("PERSISTENCE_LAYER_PERSIST_STATE_ERROR", CONSTANT_PREFIX)
  lazy val PERSISTENCE_LAYER_PERSIST_STATE_SUCCESS: String = Constants.getString("PERSISTENCE_LAYER_PERSIST_STATE_SUCCESS", CONSTANT_PREFIX)
  lazy val PERSISTENCE_LAYER_PERSIST_EVENT: String = Constants.getString("PERSISTENCE_LAYER_PERSIST_EVENT", CONSTANT_PREFIX)
  lazy val PERSISTENCE_LAYER_PERSIST_SUCCESS: String = Constants.getString("PERSISTENCE_LAYER_PERSIST_SUCCESS", CONSTANT_PREFIX)
  lazy val PERSISTENCE_LAYER_PERSIST_EVENT_RETRY: String = Constants.getString("PERSISTENCE_LAYER_PERSIST_EVENT_RETRY", CONSTANT_PREFIX)
  lazy val PERSISTENCE_LAYER_PERSIST_EVENT_ERROR: String = Constants.getString("PERSISTENCE_LAYER_PERSIST_EVENT_ERROR", CONSTANT_PREFIX)
  lazy val PERSISTENCE_LAYER_UNKNOWN_MSG: String = Constants.getString("PERSISTENCE_LAYER_UNKNOWN_MSG", CONSTANT_PREFIX)
  lazy val RECOVERED_UNDEFINED_ROLE: String = Constants.getString("RECOVERED_UNDEFINED_ROLE", CONSTANT_PREFIX)
}
